### PR TITLE
Update pk.srt

### PR DESCRIPTION
**Pull request by toinhoalam**
I translated a later scene following the pattern you started.

### CODE REVIEW

**Comment by toinhoalam** [comment]
I noticed there are some lines of dialogue missing in those subtitles. Should we search for another one or let them be?

**Review by stefichjo — CHANGES_REQUESTED** [review]
Thank you so much. :)
In order to make the toki pona style coherent/consistent (before we can start to improve the translations themselves), please:

- tokiponize according to: http://tokipona.net/tp/janpije/tpize.php
- use digits for numbers higher than 2. This is also because there is more than one way to express numbers with words.
- use the "anu seme" instead of the alternative way "... ala ...".
- skip "lon" in "la"-phrases.
- use a comma after sentences before "la"
- use "a", "ale", "lukin", "sin" instead of "kin", "ali", "oko", "namako"

187: since "suwi" comes from "sweet", "sweeti" should be "Suwisi".
187: conserve number of syllables during tokiponization: "Lamesi" → "Lame"
188: tu wan → 3
191: jo ala jo → "jo ... anu seme"
195: wile ala wile → wile ... anu seme
201: lon ni la → ni la
202: kin → a
205: lukin ala lukin → lukin ... anu seme
213: wile ala wile → wile ... anu seme
214: ... pana sona*,* la
216: ... ma ni*,* la
216: kin → a

**Comment by stefichjo** [comment]
I couldn't find a better version of the subtitles. I suppose the original subtitles didn't have entries for some lines. (For example the old man in front of the theater in Belgium shouting "security!".) For me, this is OK.

**Comment by toinhoalam** [comment]
pona. Please review my other pull request, or just accept it and close it... Trust me, I followed your guidelines :) Now I see that I can make new commits to this already pulled request, so no need to open a new request (noob me :P)

**Comment by toinhoalam** [comment]
I will be translating random scenes to avoid conflict with your stream of work. Otherwise maybe I would start editing a part you have already started...

**Comment by stefichjo** [comment]
Great! Thank you so much. And this GitHub web interface is working really well. (I'm used to the command-line interface.)

**Pull request merged**
